name: invia_hotel_booking
description: >-
  This project was developed as part of an Invia interview assignment to demonstrate proficiency in Flutter development, 
  clean architecture principles, and best practices. The app showcases a hotel booking interface with a bottom 
  navigation bar featuring four tabs: Overview, Hotels, Favorites, and Account. It implements state management with 
  BLoC pattern, efficient navigation, persistent storage, and comprehensive test coverage.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
    
  # UI/Widgets
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  gap: ^3.0.1
  google_fonts: ^6.2.1
  shimmer: ^3.0.0
  
  # Routing
  app_links: ^6.4.0
  auto_route: ^9.0.3
  
  # State Management
  flutter_bloc: ^9.1.0
  hydrated_bloc: ^10.0.0
  
  # Networking
  connectivity_plus: ^6.1.3
  dio: ^5.8.0+1
  
  # Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path: ^1.9.1
  path_provider: ^2.1.5
  
  # Utilities
  dartz: ^0.10.1
  equatable: ^2.0.7
  intl: ^0.19.0
  
  # Dependency Injection
  get_it: ^8.0.3
  injectable: ^2.5.0
  
  # Serialization
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  # Linting
  flutter_lints: ^5.0.0
  
  # Code Generation
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.15
  hive_generator: ^2.0.1
  injectable_generator: ^2.1.0
  json_serializable: ^6.9.0
  
  # Testing
  bloc_test: ^10.0.0
  mocktail: ^1.0.4
  network_image_mock: ^2.1.1

flutter:
  uses-material-design: true
  generate: true