name: invia_hotel_booking
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  auto_route: ^9.0.3
  intl: ^0.19.0
  connectivity_plus: ^6.1.3
  get_it: ^8.0.3
  injectable: ^2.5.0
  dio: ^5.8.0+1
  equatable: ^2.0.7
  path: ^1.9.1
  path_provider: ^2.1.5
  flutter_localizations:
    sdk: flutter
  json_annotation: ^4.9.0
  dartz: ^0.10.1
  flutter_bloc: ^9.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_screenutil: ^5.9.3
  cached_network_image: ^3.4.1
  gap: ^3.0.1
  shimmer: ^3.0.0
  google_fonts: ^6.2.1
  hydrated_bloc: ^10.0.0
  app_links: ^6.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  auto_route_generator: ^9.0.0
  injectable_generator: ^2.1.0
  json_serializable: ^6.9.0
  hive_generator: ^2.0.1
  mocktail: ^1.0.4
  bloc_test: ^10.0.0
  network_image_mock: ^2.1.1

flutter:
  uses-material-design: true
  generate: true