name: invia_hotel_booking
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  auto_route: ^10.0.1
  intl: ^0.19.0
  connectivity_plus: ^6.1.3
  get_it: ^8.0.3
  injectable: ^2.5.0
  dio: ^5.8.0+1
  objectbox: ^4.1.0
  objectbox_flutter_libs: ^4.1.0
  path_provider: ^2.1.5
  path: ^1.9.1
  flutter_localizations:
    sdk: flutter

dependency_overrides:
  source_gen: 2.0.0
  dart_style: 3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  auto_route_generator: ^10.0.1
  injectable_generator: ^2.7.0
  json_serializable: ^6.9.4
  objectbox_generator: ^4.1.0

flutter:
  uses-material-design: true
  generate: true